[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9.2"
dependencies = [
    "clerk-backend-api>=2.2.0",
    "fastapi>=0.116.1",
    "google-generativeai>=0.8.6",
    "openai>=1.96.1",
    "python-dotenv>=1.0.1",
    "sqlalchemy>=2.0.41",
    "svix>=1.76.1",
    "uvicorn>=0.33.0",
]
